### ISSUE TITLE
Question: Would this specific model X-Y slide holder fit the puma scope? I noticed there was not one listed in the non-printed-parts.

### ISSUE THREAD

**Issue by liquidbear99** [TadPath/PUMA#14]
Hello, I have just built the basic microscope and am looking to upgrade it a bit! I noticed there was no recommended/example x-y slide holder and it may be worth adding this to the excel document if it would fit.

Do you know if this would fit?
https://www.aliexpress.com/item/1904300031.html?spm=a2g0o.cart.0.0.40f33c00HrxRq6&mp=1

**Comment by TadPath** [comment]
Nice to hear you made one - hope the experience and end result are satisfying. Do post on social media your experiences to help raise awareness. Re upgrades - there is too much detail to write about so I put these in the videos as I make them. This XY will fit the holes in the stage but the curved arm will be too long - you would need to truncate it in a correct way to avoid it snagging on the front focus post (truncate it in the wrong way and you loose functionality). I will provide details when I do the video on stage accessories. This type also needs correct application of the XY stabiliser - again there are important details that will need to wait for the video. As stated in the intro github readme, upgrade modules may get revised while I make tutorials so be aware that some models and instruction may change by then (for the better). So I update all Github docs (Excel, FreeCAD files, 3DPrinting guide) for each upgrade as I make each tutorial. Thanks for your interest in the project.

**Comment by liquidbear99** [comment]
No worries! I appreciate the effort on this project. It is quite amazing the quality that I have from just the base model. I did also want to recommend you visit the link provided here for the 23mm convex lens. This link is the same product as the ebay one you provide, but is cheaper on Aliexpress. https://www.aliexpress.com/item/1924222603.html?spm=a2g0o.order_list.0.0.21ef1802SxBDkC

On a side note, if there is any way I could become more involved in development or helping this project let me know. I am thinking about writing a review article on my assembly process and concerning the possible medical implications of this device even though it holds no formal certification (I am a current medical student).

**Comment by TadPath** [comment]
Thanks. If you want to contact me to discuss the project you can use my doctors.org.uk email (the one in the J. Microsc. paper - it will be more convenient for me). BTW you should read the J Microsc. article if you have not done so already.
As a medical student I don't want to distract you from your studies - I dropped all contact with computers and programming when I went to med school in the 1980s to concentrate on my studies but I suppose things are different now. You can help simply by spreading the word on social media and among your peers and tutors. A review article sounds like a good idea and hopefully you will get it published but it sounds like an awful lot of work.
The lens that is bugging me right now is the 30 mm lens because it has come to my attention that there are various 'shapes' available from different sellers so I left a note in the video description of the Abbe condenser video to advise people which to look out for but I am working on that a bit more.

**Comment by liquidbear99** [comment]
Super, I just requested it the other day from our library and I have plans to read it in the near future!
