### ISSUE TITLE
Quick start guide?

### ISSUE THREAD

**Issue by InnerLive** [TadPath/PUMA#17]
Is there anything like a quick start guide so that I know what I need to print to build configuration 1 myself?
Maybe I missed this, but I'm a little lost. What are the minimum parts I need to print?
And preferably the matching hardware that needs to be purchased.

Thanks for the great work!

**Comment by TadPath** [comment]
Not yet as such - but I realise I need to do this because you are not the first to ask. In the mean time the best way to get started is a combination of the following:

1. Get familiar with the Bill_of_Materials spreadsheet - this has a full list of the specific parts (3D printed and purchased hardware) you need for each module and for each of 3 typical configurations of completed microscope (a 'configuration' is made up of a collection of modules). It also has some example URLs where you can purchase specific non-printed parts on AliExpress and eBay, etc.
2. Get familiar with the 3D printing guide PDF - read the intro pages and look at a few of the models pages.
The Foundation Scope user manual PDF is freely available for download from the Optarc.co.uk site - that may also help.
3. Once you have seen these docs you can begin by looking at the videos on 'How to Build the Stage ...', then 'Z-Stage II - Troubleshooting and maintenance'.
4. Once you have built a working stage you have done most of the work needed to make a PUMA microscope. To finish off just see the video on 'How to Build a Foundation scope' - and you should be done. The 'Field strip' and 'Assembly' videos will also be useful watching at this stage. The rest are all about various upgrades and add-ons (and more videos are on the way!)

All the best!

**Comment by TadPath** [comment]
If you see the BoM spreadsheet there is a worksheet near the end called 'CF_Monocular_Mirror_Scope' (this is the simplest 'Foundation scope' config). In the 'Modules' column of that worksheet it lists the modules you need to build for that config. So it currently shows this list:
Stage
Legs_short
Stage_clips
Mirror_Simple
Objective_x40 [Note: this is a typo - it should be x4 not x40 - I will fix it]
Filterblock_simple
Monocular_head
Ocular_lens

Each member of the above list refers to a worksheet in the same spreadsheet which you need to refer to to get the parts to print. For example, 'Stage' refers to the worksheet called: 'MD_Stage' and that worksheet shows you all the 'STL' files you need to print to build that module plus all the non-printed parts you need to get. So, to get everything you need to print and all other hardware you need for a complete scope, just go down the above list and see the 'MD_' module worksheet for each one.
Please see the 3D Print guide PDF for each model before printing to see if there are any special requirements - orientation on the build plate should be as shown in the picture, supports, etc. should be as for the Cura profile for the model (in general use the 'Flats' profile unless specified otherwise. You can download the profiles from the 3D printing part of this GitHub. If you don't use Cura or Ender3 it will be up to use to devise a suitable 'equivalent' profile for your slicer/printer but you can (and I advise should) use the Cura profiles I provide as a template/guide for that.
My videos will show you what to do with all the parts to put them together - this is important because the correct assembly technique is not obvious from looking at the parts.
The stage is the single most complex thing so perhaps before you print all parts for a whole microscope, just attempt to build the stage and see how it goes. If you can get a working stage, the other stuff should be relatively easy and quick to add.

**Comment by InnerLive** [comment]
I have cross-read the PDF already. It looks very well done and comprehensive! I will try my luck as soon as possible.
Thanks a lot!
