### ISSUE TITLE
Prefer additive manufacturing format (amf) to STL

### ISSUE THREAD

**Issue by plaes** [TadPath/PUMA#18]
Current 3D Printing guide suggests using STL files as intermediate format for 3D-printing and although it works, this format has various shortcomings that have been addressed in the [AMF](https://en.wikipedia.org/wiki/Additive_manufacturing_file_format). AMF is also an open standard.

FreeCAD also supports exporting AMF, just make exportable object (or body) active and from menu select File -> Export and select "Additive Manufacturing Format (*.amf)" as a type. This would allow to clean up the whole mesh preparation process from the documentation.

Although my 3D-printing process does not involve Cura (I'm using PrusaSlicer), I'm pretty sure it's also supported there.

**Comment by TadPath** [comment]
Yes - I agree that other formats may be better for some uses which is one of the reasons I chose not to publish STLs but full FreeCAD models (so people can chose which format they prefer for printing, as well as to make the scope easier to customise). Cura supports AMF files as well. I use the example of STL in my docs only because it is very commonly used in the home/school/college 3D print community. I myself have not tried using AMF though so I don't have personal experience of it. Perhaps I can put a note about alternative formats in the 3D Printing Guide for completeness when I next update it. Thanks.
