### ISSUE TITLE
JST XH PCB headers

### ISSUE THREAD

**Issue by GanescuStefan** [TadPath/PUMA#21]
Hello,

I am currently trying to build the PCC.
In the component section of both the PCC and of the motherboard, it mentions that the JST XH PCB connector headers should be the right angled versions only, however in some images the connectors are straight. For example, on this motherboard image there are 7 straight connectors and 2 right angled ones, even though the specification says they should all be right angled. 

![MB_TP_Components](https://user-images.githubusercontent.com/71331265/176206094-11b23487-ef03-446d-aa02-f243a867d33e.png)

Is this an error with the required components, or would it be best to use the right angled versions? There are less images of the PCC connectors, so I wanted to know for sure if I needed both straight and right angled headers for each of the pin numbers.

Thank you in advance.

**Comment by TadPath** [comment]
Hello. Thanks for the question. It is not an error but could do with some explanation (I would normally provide this in the videos but I haven't released a PCC video yet so, here goes):
The key thing to note here is that the way you mount them is not the same as the pin angle. Let me explain.
You mount the headers as shown in the diagram - i.e. most of them are straight up, not 90 degrees, with two exceptions as shown). However, because with the DIY motherboard you have wires running under some of the headers on the top surface of the tripad board, this means that some of the headers that are mounted straight up will need extra long pins to make it through to the underside of the board for soldering (compared to the usual straight pin headers which have very short pins).
So if you use right-angled headers, you can always straighten the pins in the header (with long nosed pliers) to get 'straight headers' with extra long pins. You an then trim the pins on the underside of the board after soldering. 
Also, for making extension cables you need the extra length provided by the (straightened out) 90 degree headers. So I advise people just buy all 90 degree headers and be done with it. If you are using the professional PCB then you can (and should) just use the straight-pin headers for those headers that are shown fitted straight up.
Does that answer your question?

**Comment by GanescuStefan** [comment]
Yes it does, thank you very much!  Then, should all of the PCC headers also be straightened, or should some stay at a right angle too?
