### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by luzpaz** [TadPath/PUMA#3]
Are there more features on the horizon?

**Comment by TadPath** [comment]
Definitely!

- A dedicated infinity adapter module that will allow the use of the SLM in the back focal plane of the objective as well as allow the use of infinity objectives from all major microscope manufacturers (as well as generics).
- I am planning to make in vitro cell culture attachment module for the stage to observe living cells.
- 3D imaging set-ups - including a robotic XYZ controller for the stage and free deconvolution software.
- More detailed 'How To' documentation. I have a video ready to relaase - just working on the subtitles now - which is the first full 'How To' guide that shows how to build the PUMA stage from scratch. It will be made public on YouTube soon.
- More demo experiment videos to teach people how to upgrade the scope and how to use its various features with practical examples.
- As @sandorkonya says, development of software for PC / Raspberry Pi to interface the SLM and AR HUD. Just because PUMA is protable doesn't mean it can't also be used as a benchtop instrument as well. In fact, the XYZ stage controller for 3D imaging will need to use a proper computer I think (RPi at least) - Arduino will not cut it.
- There is a lot more I have in mind - but how much of this is actually realised will depend on the amount of uptake and support is shown for the project from the community. I watch the response to my YouTube channel and GitHub repository and other correspondence and continually assess that. I am not big on social media so I must rely on others to spread the word if they like what I am doing to drum up support.

**Comment by luzpaz** [comment]
Awesome, perhaps tracking it using https://github.com/TadPath/PUMA/projects ?
